package com.springsecurity.nfc.constants;

public interface Queries {
	public interface Prototype {
		String GET_TABLES = "SELECT UPPER(TABLE_NAME) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA='nfc'";
		String GET_COLUMNS = "SELECT GROUP_CONCAT(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS CC WHERE CC.TABLE_SCHEMA = 'nfc' AND CC.TABLE_NAME = ? AND EXTRA <> 'AUTO_INCREMENT'";
		String GET_COLUMNS_UPATE = "SELECT GROUP_CONCAT(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS CC WHERE CC.TABLE_SCHEMA = 'nfc' AND CC.TABLE_NAME = ? AND CC.COLUMN_NAME NOT IN('CREATED_ON','CREATED_BY','MERCHANT_ID') AND EXTRA <> 'AUTO_INCREMENT'";
	}
	
	public interface merchant {
		String TXN_GRAPH = "SELECT SUM(TOTAL_AMT) AS VALUE, DATE(CREATED_ON) AS LABEL FROM TXNHISTORY WHERE MERCHANT_ID = ? AND CREATED_ON > CURRENT_TIMESTAMP - INTERVAL 10 DAY GROUP BY DATE(CREATED_ON) ORDER BY CREATED_ON";
		String MENU_GRAPH = "SELECT (SELECT NAME FROM MENU WHERE ID=MENU_ID) AS LABEL, COUNT(MENU_ID) AS VALUE FROM ORDERS WHERE MERCHANT_ID = ? AND CREATED_ON - INTERVAL 28 DAY GROUP BY MENU_ID ORDER BY CREATED_ON";
		String FOOTFALL_GRAPH = "SELECT COUNT(DISTINCT(ORDER_ID)) AS DATA, MONTHNAME(CREATED_ON) AS LABEL FROM ORDERS WHERE MERCHANT_ID = ? AND YEAR(CURDATE()) = YEAR(CURDATE()) GROUP BY MONTH(CREATED_ON)";
		String ACTIVE_MENU = "SELECT M.NAME AS MENU_NAME, O.* FROM ORDERS O, MENU M WHERE O.MERCHANT_ID = ? AND M.ID = O.MENU_ID AND STATUS = 'ACTIVE' ORDER BY ORDER_ID";
		String GET_FILTERED_MENU="SELECT * FROM MENU WHERE MERCHANT_ID = P1 AND NAME LIKE '%P2%' ORDER BY SORTORDER";
		String GET_ALL_MENU="SELECT * FROM MENU WHERE MERCHANT_ID = P1 ORDER BY SORTORDER";
		String GET_MENU_ID_BY_ORDER_ID = "SELECT GROUP_CONCAT(MENU_ID) FROM ORDERS WHERE ORDER_ID = ?";
		String UPDATE_QUANTITY_BY_MENU_ID = "UPDATE ORDERS SET QUANTITY = ?, AMOUNT = ? WHERE ORDER_ID = ? AND MENU_ID = ?";
		String SINGLE_ORDER = "SELECT M.NAME AS MENU_NAME, O.* FROM ORDERS O, MENU M WHERE  M.ID = O.MENU_ID AND O.MERCHANT_ID = ? AND ORDER_ID = ?";
		String GET_CATEGORIES="SELECT * FROM CATEGORY WHERE (MERCHANT_ID = ? OR SORTORDER LIKE '99%') AND LEVELNUMBER = ? AND SORTORDER LIKE ? ORDER BY SORTORDER";
		String GET_MAX_SORTORDER="SELECT MAX(SORTORDER) FROM CATEGORY WHERE MERCHANT_ID = ? AND LEVELNUMBER = ? AND SORTORDER LIKE ? AND SORTORDER NOT LIKE '99%'";
		
	}
	
}