package com.springsecurity.common.query;

public interface AuthQueries {
	String IS_USER_EXIST = "SELECT PASSWORD FROM USER WHERE LOGINNAME = ?";
	String GET_USER_DETAILS = "SELECT U.ID AS UID, U.USERNAME, U.PASSWORD, U.STATUS, U.LOGINNAME, U.EMAIL, U.DOB, R.ID, R.ROLENAME FROM USER U, ROLE R, USERSANDROLES UR WHERE U.LOGINNAME = ? AND U.ID = UR.USER_ID AND R.ID = UR.ROLE_ID";
	String GET_USER_MENU = "SELECT * FROM PMENU WHERE ROLE_ID = ? or ROLE_ID=9 ORDER BY IDENTIFIER";
}
